package friends;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;

public class VentanaPrincipal extends javax.swing.JFrame {

    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        read = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setText("Nombre");

        number.setText("Numero");

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        read.setText("Read");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(read)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number)
                            .addComponent(name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNumber))
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumber)
                    .addComponent(number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(read)
                    .addComponent(update)
                    .addComponent(delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

        try {
            
            String newName = txtName.getText();
            long newNumber = Long.parseLong(txtNumber.getText());
            String nameNumberString;
            String name;
            long number;
            int index;
            
            File file = new File("FriendsContact.txt");
            
            if (!file.exists()) {
                
                file.createNewFile();
                
            }
            
            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;
            
            while (raf.getFilePointer() < raf.length()) {
            
                nameNumberString = raf.readLine();
                
                String[] lineSplit = nameNumberString.split("!");
                
                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
                
                if (name == newName || number == newNumber) {
                    
                    found = true;
                    break;
                    
                }
                            
            }
            
            if (found == false) {
                
                nameNumberString = newName + "!" + String.valueOf(newNumber);
                
                raf.writeBytes(nameNumberString);
                
                raf.writeBytes(System.lineSeparator());
                
                JOptionPane.showMessageDialog(null, "Friend added", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                
                raf.close();
                
            }
            
            else {
                
                raf.close();
                
                JOptionPane.showMessageDialog(null, "Friend does not exist", "ERROR", JOptionPane.ERROR_MESSAGE);
                
            }
            
        }
        
        catch (IOException ioe) {
            
            JOptionPane.showMessageDialog(null, ioe, "ERROR", JOptionPane.ERROR_MESSAGE);
             
        }
        
        catch (NumberFormatException nef) {
            
            JOptionPane.showMessageDialog(null, nef, "ERROR", JOptionPane.ERROR_MESSAGE);
            
        }

    }//GEN-LAST:event_createActionPerformed

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
    
        try {

            String newName = txtName.getText();
            String nameNumberString;
            String name;
            long number;
            int index;
            
            File file = new File("FriendsContact.txt");
            
            if (!file.exists()) {
                
                file.createNewFile();
                
            }
            
            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;
            
            while (raf.getFilePointer() < raf.length() ) {
                
                nameNumberString = raf.readLine();
                
                String[] lineSplit = nameNumberString.split("!");
                
                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
                
                if (name.equals(newName)) {
                    
                    txtNumber.setText(String.valueOf(number));
                    
                }

            }
            
        }
        
        catch (IOException ioe) {
            
            JOptionPane.showMessageDialog(null, ioe, "ERROR", JOptionPane.ERROR_MESSAGE);
             
        }
        
        catch (NumberFormatException nef) {
            
            JOptionPane.showMessageDialog(null, nef, "ERROR", JOptionPane.ERROR_MESSAGE);
            
        }
            
    }//GEN-LAST:event_readActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        try {

            String newName = txtName.getText();
            long newNumber = Long.parseLong(txtNumber.getText());
            String nameNumberString;
            String name;
            long number;
            int index;
            
            File file = new File("FriendsContact.txt");
            
            if (!file.exists()) {
                
                file.createNewFile();
                
            }
            
            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;
            
            while (raf.getFilePointer() < raf.length()) {
            
                nameNumberString = raf.readLine();
                
                String[] lineSplit = nameNumberString.split("!");
                
                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
                
                if (name.equals(newName) || number == newNumber) {
                    
                    found = true;
                    break;
                    
                }
                            
            }
            
            if (found == true) {
                
                File tmpFile = new File("temp.txt");
                
                RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");
                
                raf.seek(0);
                
                while (raf.getFilePointer() < raf.length()) {
                    
                    nameNumberString = raf.readLine();
                    
                    index = nameNumberString.indexOf("!");
                    name = nameNumberString.substring(0, index);
                    
                    if (name.equals(newName)) {
                        
                        nameNumberString = name + "!" + String.valueOf(newNumber);
                        
                    }
                    
                    tmpraf.writeBytes(nameNumberString);
                    tmpraf.writeBytes(System.lineSeparator());
                    
                }
                
                raf.seek(0);
                tmpraf.seek(0);
                
                while (tmpraf.getFilePointer() < tmpraf.length()) {
                    
                    raf.writeBytes(tmpraf.readLine());
                    raf.writeBytes(System.lineSeparator());
                    
                }
                
                raf.setLength(tmpraf.length());
                
                tmpraf.close();
                raf.close();
                
                tmpFile.delete();
                
                JOptionPane.showMessageDialog(null, "Friend updated", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
            else {
                
                raf.close();
                
                JOptionPane.showMessageDialog(null, "Friend does not exist", "ERROR", JOptionPane.ERROR_MESSAGE);
                
            }
            
        }
        
        catch (IOException ioe) {
            
            JOptionPane.showMessageDialog(null, ioe, "ERROR", JOptionPane.ERROR_MESSAGE);
             
        }
        
        catch (NumberFormatException nef) {
            
            JOptionPane.showMessageDialog(null, nef, "ERROR", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try {
            
            String newName = txtName.getText();
            String nameNumberString;
            String name;
            long number;
            int index;
            
            File file = new File("FriendsContact.txt");
            
            if (!file.exists()) {
                
                file.createNewFile();
                
            }
            
            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;
            
            while (raf.getFilePointer() < raf.length()) {
                
                nameNumberString = raf.readLine();
                
                String[] lineSplit = nameNumberString.split("!");
                
                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
                
                if (name.equals(newName)) {
                    
                    found = true;
                    break;
                    
                }
                
            }
            
            if (found == true) {
                
                File tmpFile = new File("temp.txt");
                
                RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");
                
                raf.seek(0);
                
                while (raf.getFilePointer() < raf.length()) {
                    
                    nameNumberString = raf.readLine();
                    
                    index = nameNumberString.indexOf("!");
                    name = nameNumberString.substring(0, index);
                    
                    if (name.equals(newName)) {
                        
                        continue;
                        
                    }
                    
                    tmpraf.writeBytes(nameNumberString);
                    
                    tmpraf.writeBytes(System.lineSeparator());
                    
                }
                
                raf.seek(0);
                tmpraf.seek(0);
                
                while (tmpraf.getFilePointer() < tmpraf.length()) {
                    
                    raf.writeBytes(tmpraf.readLine());
                    raf.writeBytes(System.lineSeparator());
                    
                }
                
                raf.setLength(tmpraf.length());
                
                tmpraf.close();
                raf.close();
                
                tmpFile.delete();
                
                JOptionPane.showMessageDialog(null, "Friend deleted", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
            else {
                
                raf.close();
                
                JOptionPane.showMessageDialog(null, "Friend does not exist", "ERROR", JOptionPane.ERROR_MESSAGE);
                
            }
            
        }
        
        catch (IOException ioe) {
            
            JOptionPane.showMessageDialog(null, ioe, "ERROR", JOptionPane.ERROR_MESSAGE);
             
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        
        txtName.setText("");
        txtNumber.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JLabel name;
    private javax.swing.JLabel number;
    private javax.swing.JButton read;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
